logging:
  config: classpath:logback-spring.xml
  file:
    path: /opt/torch/data
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: info,health
nexus:
  base:
    url: /nexus/skeleton
  disable:
    auth: false
server:
  port: 8080
spring:
  application:
    name: skeleton-Micro-service
